# Recorder Demo
In this notebook we demonstrate how to use the recorders to load the different data sources.

## Imports

In [1]:
import sys
sys.path.insert(0,'../..')  # Set src as top-level

import pandas as pd

In [2]:
# Own library
from src.recorders.coil_recorder import CoilRecorder
from src.recorders.ssd_recorder import SSDRecorder
from src.recorders.laser_recorder import LaserRecorder
from src.recorders.file_recorder import FileRecorder
from src.recorders.gauge_recorder import GaugeRecorder
from src.recorders.ion_recorder import IonRecorder
from src.recorders.heater_recorder import HeaterRecorder
from src.recorders.pmt_recorder import PMTRecorder

In [3]:
# Relative path
rel_path = "../../data/sample/"

## Coil Recorder
Allows us to know the status of the coil at any time.

In [4]:
coil_recorder = CoilRecorder(filepath=rel_path + "coil_log.txt")

In [5]:
coil_df = coil_recorder.get_table()
coil_df.head(5)

                  Time CoilOperation             datetime            timestamp
0  2022/03/14 12:09:23            ON  2022/03/14 12:09:23  1647259763000000000
1  2022/03/14 12:09:23           OFF  2022/03/14 12:09:23  1647259763000000000
2  2022/03/14 12:09:31            ON  2022/03/14 12:09:31  1647259771000000000
3  2022/03/14 12:10:53           OFF  2022/03/14 12:10:53  1647259853000000000
4  2022/03/14 12:12:57           OFF  2022/03/14 12:12:57  1647259977000000000

## SSD Recorder
Allows us to load the pulses.

In [6]:
ssd_recorder = SSDRecorder(filepath=rel_path + "-20220314-100806-Slot1-In2.csv")

In [7]:
ssd_df = ssd_recorder.get_data()
ssd_df.head(5)

   TraceName   Time_x  PulseHeight
0          0   553786         2463
1          1   865236         2855
2          2  2486115         2516
3          3  2628986         2527
4          4  2650471         2456

In [8]:
ssd_df_table = ssd_recorder.get_table()
ssd_df_table.head(5)

,TraceName,Time_x,PulseHeight,Model,BlockNumber,BlockSize,VUnit,HResolution,HUnit,Date,...,//SignalType,//Synchronize,//StopSource,//TimeResolution,//TimeStamp,//RealTime,//LiveTime,//DeadTime(%),timestamp,datetime
0,0,553786,2463,WE7562,1,15262,cnt,1.000000e+000,?,2022/03/14,...,Trigger,OFF,None,1.000000e-006,Peak,7.136569e+003,7.136410e+003,2.233544e-003,1.647252e+18,2022-03-14 11:07:54
1,1,865236,2855,WE7562,1,15262,cnt,1.000000e+000,?,2022/03/14,...,Trigger,OFF,None,1.000000e-006,Peak,7.136569e+003,7.136410e+003,2.233544e-003,1.647252e+18,2022-03-14 11:07:54
2,2,2486115,2516,WE7562,1,15262,cnt,1.000000e+000,?,2022/03/14,...,Trigger,OFF,None,1.000000e-006,Peak,7.136569e+003,7.136410e+003,2.233544e-003,1.647252e+18,2022-03-14 11:07:56
3,3,2628986,2527,WE7562,1,15262,cnt,1.000000e+000,?,2022/03/14,...,Trigger,OFF,None,1.000000e-006,Peak,7.136569e+003,7.136410e+003,2.233544e-003,1.647252e+18,2022-03-14 11:07:56
4,4,2650471,2456,WE7562,1,15262,cnt,1.000000e+000,?,2022/03/14,...,Trigger,OFF,None,1.000000e-006,Peak,7.136569e+003,7.136410e+003,2.233544e-003,1.647252e+18,2022-03-14 11:07:56

## Laser Recorder
Allows us to know the frequency of the six laser signals.

In [9]:
laser_recorder = LaserRecorder(filepath=rel_path + "15.03.2022, 21.30, 384.22817013 THz.lta")

In [10]:
laser_df = laser_recorder.get_table()
laser_df.head(5)

,Time [ms],"Signal 8 Wavelength, vac. [nm]","Signal 1 Wavelength, vac. [nm]","Signal 4 Wavelength, vac. [nm]","Signal 6 Wavelength, vac. [nm]","Signal 3 Wavelength, vac. [nm]","Signal 2 Wavelength, vac. [nm]",Title,File version,Version,...,LTWH,Docked,Color,LColor,KyM,yMM,Exp,ExpC,timestamp,datetime
0,493.7473,780.245909,780.246040,794.969235,718.216332,817.098723,718.136908,WLMLTAID02,8,"9,4310,6508,001",...,"0,1000,1072,271",1,7901332,16777215,2,"-13,-13",1,1,1.647334e+18,2022-03-15 09:46:39
1,987.6469,780.245909,780.246041,794.969150,718.216331,817.098719,718.136910,WLMLTAID02,8,"9,4310,6508,001",...,"0,1000,1072,271",1,7901332,16777215,2,"-13,-13",1,1,1.647334e+18,2022-03-15 09:46:39
2,1481.4935,780.245909,780.246040,794.969186,718.216333,817.098724,718.136907,WLMLTAID02,8,"9,4310,6508,001",...,"0,1000,1072,271",1,7901332,16777215,2,"-13,-13",1,1,1.647334e+18,2022-03-15 09:46:39
3,1975.3737,780.245909,780.246039,794.969171,718.216329,817.098724,718.136915,WLMLTAID02,8,"9,4310,6508,001",...,"0,1000,1072,271",1,7901332,16777215,2,"-13,-13",1,1,1.647334e+18,2022-03-15 09:46:39
4,2469.2408,780.245909,780.246041,794.969131,718.216332,817.098719,718.136905,WLMLTAID02,8,"9,4310,6508,001",...,"0,1000,1072,271",1,7901332,16777215,2,"-13,-13",1,1,1.647334e+18,2022-03-15 09:46:39

## File Recorder
Allows us to find all files which match a certain regex pattern.

In [11]:
file_recorder = FileRecorder(filepath=rel_path, match=".*.csv")

In [12]:
file_df = file_recorder.get_table()
file_df.head(5)

,filename,filename_with_extension,filepath,mtime,ctime,timestamp,datetime
1,-20220314-100806-Slot1-In2,-20220314-100806-Slot1-In2.csv,../../data/sample/-20220314-100806-Slot1-In2.csv,1.662094e+09,1.661918e+09,2022-08-31 05:55:40.128582,2022-08-31 05:55:40.128582
5,HeaterLog_20220314_100740_00001,HeaterLog_20220314_100740_00001.csv,../../data/sample/HeaterLog_20220314_100740_00...,1.661841e+09,1.661918e+09,2022-08-31 05:55:40.134582,2022-08-31 05:55:40.134582
0,IonBeamControl1.5_DESKTOP-8ICG2TJ_20220314_114132,IonBeamControl1.5_DESKTOP-8ICG2TJ_20220314_114...,../../data/sample/IonBeamControl1.5_DESKTOP-8I...,1.661841e+09,1.661918e+09,2022-08-31 05:55:40.142624,2022-08-31 05:55:40.142624
4,TPG256GaugeMonitor_Single_DESKTOP-BEF5FI4_2022...,TPG256GaugeMonitor_Single_DESKTOP-BEF5FI4_2022...,../../data/sample/TPG256GaugeMonitor_Single_DE...,1.661841e+09,1.661918e+09,2022-08-31 05:55:40.149593,2022-08-31 05:55:40.149593
3,all_data,all_data.csv,../../data/sample/all_data.csv,1.661926e+09,1.661918e+09,2022-08-31 05:56:13.689477,2022-08-31 05:56:13.689477

## Gauge Recorder

In [13]:
gauge_recorder = GaugeRecorder(filepath=rel_path + "TPG256GaugeMonitor_Single_DESKTOP-BEF5FI4_20220312_203214.csv")

In [14]:
gauge_df = gauge_recorder.get_table()
gauge_df.head(5)

,Timestamp,Rb disp.,Neut.,Surf. Ref.,NC1,NC2,NC3,datetime,timestamp
0,2022/03/12 20:32:19,8.950000e-07,0.000001,8.270000e-07,1.000000e-09,0.05009,0.05009,2022-03-12 20:32:19,1647117139000000000
1,2022/03/12 20:32:20,8.930000e-07,0.000001,8.260000e-07,1.000000e-09,0.05009,0.05009,2022-03-12 20:32:20,1647117140000000000
2,2022/03/12 20:32:21,8.910000e-07,0.000001,8.280000e-07,1.000000e-09,0.05009,0.05009,2022-03-12 20:32:21,1647117141000000000
3,2022/03/12 20:32:22,8.950000e-07,0.000001,8.280000e-07,2.000000e-07,0.05009,0.05009,2022-03-12 20:32:22,1647117142000000000
4,2022/03/12 20:32:23,8.940000e-07,0.000001,8.270000e-07,2.000000e-07,0.05009,0.05009,2022-03-12 20:32:23,1647117143000000000

## Ion Recorder

In [15]:
ion_recorder = IonRecorder(filepath=rel_path + "IonBeamControl1.5_DESKTOP-8ICG2TJ_20220314_114132.csv")

In [16]:
ion_df = ion_recorder.get_table()
ion_df.head(5)

,Timestamp,Be Bypass,Fr Beamline,Center,Surrounding,FC,NC,Be temp (degC),He press (V),Au temp (V),...,Def Down Current,Drift 1 Current,Einzel Current,Drift 2 Current,Freq (kHz),Phase (deg),Amp(CH1) (Vpp),Amp(CH2) (Vpp),datetime,timestamp
0,2022/03/14 11:41:38,0.00201,0.000044,0.0,0.0,-0.000301,0.0,0.00005,3.0185,0.71115,...,-1.200000e-07,-1.400000e-07,-2.800000e-07,4.000000e-08,0,0,0,0,2022-03-14 11:41:38,1647258098000000000
1,2022/03/14 11:41:39,0.00201,0.000044,0.0,0.0,0.000835,0.0,0.00005,3.0175,0.71115,...,-1.200000e-07,-1.400000e-07,-2.700000e-07,4.000000e-08,0,0,0,0,2022-03-14 11:41:39,1647258099000000000
2,2022/03/14 11:41:40,0.00201,0.000044,0.0,0.0,0.000641,0.0,0.00005,3.0175,0.71115,...,-1.200000e-07,-1.400000e-07,-2.700000e-07,4.000000e-08,0,0,0,0,2022-03-14 11:41:40,1647258100000000000
3,2022/03/14 11:41:41,0.00201,0.000043,0.0,0.0,0.001132,0.0,0.00005,3.0175,0.71115,...,-1.200000e-07,-1.400000e-07,-2.700000e-07,3.000000e-08,0,0,0,0,2022-03-14 11:41:41,1647258101000000000
4,2022/03/14 11:41:42,0.00200,0.000043,0.0,0.0,0.000448,0.0,0.00005,3.0180,0.71115,...,-1.200000e-07,-1.400000e-07,-2.700000e-07,3.000000e-08,0,0,0,0,2022-03-14 11:41:42,1647258102000000000

## PMT Recorder
Allows us to access the PMT current and the ROI sum.

In [17]:
pmt_recorder = PMTRecorder(filepath=rel_path + "all_data.csv")

In [18]:
pmt_df = pmt_recorder.get_table()
pmt_df.head(5)

,No.,Time,PMT Current (A),ROI Sum,Coil (1:ON 0:OFF),datetime,timestamp
0,1,2022/03/15 08:18:00.266,-1.519308e-13,1491678,1,2022/03/15 08:18:00.266,1647332280266000000
1,14,2022/03/15 08:18:01.507,9.085866e-13,1498276,1,2022/03/15 08:18:01.507,1647332281507000000
2,18,2022/03/15 08:18:01.907,3.832096e-13,1499445,1,2022/03/15 08:18:01.907,1647332281907000000
3,22,2022/03/15 08:18:02.308,3.028373e-15,1499770,1,2022/03/15 08:18:02.308,1647332282308000000
4,26,2022/03/15 08:18:02.710,4.986230e-14,1498276,1,2022/03/15 08:18:02.710,1647332282710000000